version: 2
jobs:
  build:
    working_directory: /go/src/github.com/lpbearden/go_results_bot
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run: go build -o bin/tweeter